### ISSUE TITLE
VSTS Dashboard not updating build Status until we refresh the page.

### ISSUE THREAD

**Issue by aravindkumaremis** [emisgroup/vsts-dashboard#70] opened 2018-06-07 12:13 UTC
I have submitted a branch for build and I can see the build progress in VSTS Dashboard, But once the build finished, it's not updated the Board. I manually refreshed the dashboard to see the result.  Will Check again and try to share screenshots.

**Comment by MarkGaze** [comment] 2018-06-07 12:16
Linked to #57

**Comment by benmatselby** [comment] 2018-06-12 12:48
Mark and I have reviewed this item, and will close as a duplicate of #57.. Please follow #57 for further updates @aravindkumaremis. Thank you very much for raising this.

**Closed by benmatselby** 2018-06-12 12:48 UTC
Labels: bug
